export const userConstants = {
  REGISTER_REQUESTS: 'USERS_REGISTER_REQUESTS',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUESTS: 'USERS_LOGIN_REQUESTS',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

}
